#!/usr/bin/env python3
"""tools/bin2c.py — real-libc-syscall-layer.md §M32.

procsrv가 musl-exec-target ELF의 원본 바이트를 VFS(memfs)에 쓰려면
그 바이트가 procsrv 자신의 컴파일 시점 데이터로 있어야 한다(런타임에
디스크에서 읽어올 수단이 없다 — 그건 애초에 이 파일이 만들려는
파일이다). 이 스크립트는 임의의 바이너리 파일을 C++ 헤더 하나(바이트
배열 + 길이 상수)로 그대로 옮긴다. 커널이 initrun.elf를 자기 이미지에
심는 .incbin(kernel/arch/x86_64/CMakeLists.txt)과 같은 목적이지만,
procsrv는 일반 유저 프로세스라 어셈블러 .incbin을 쓸 수 없어(빌드
드라이버가 다르다) 대신 이 방식을 쓴다.

사용법: bin2c.py <입력 바이너리> <출력 헤더> <배열 이름>
"""
import sys


def main(argv):
    if len(argv) != 4:
        sys.stderr.write("usage: bin2c.py <input> <output.h> <array_name>\n")
        return 1
    in_path, out_path, array_name = argv[1], argv[2], argv[3]
    with open(in_path, "rb") as f:
        data = f.read()
    lines = []
    lines.append(f"// Auto-generated by tools/bin2c.py from {in_path} -- do not edit.\n")
    lines.append("#pragma once\n")
    lines.append("#include <cstdint>\n\n")
    lines.append(f"inline constexpr uint64_t {array_name}_len = {len(data)}ull;\n")
    lines.append(f"inline constexpr unsigned char {array_name}[] = {{\n")
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append(", ".join(str(b) for b in chunk) + ",\n")
    lines.append("};\n")
    with open(out_path, "w", newline="\n") as f:
        f.writelines(lines)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
